export XDG_RUNTIME_DIR="$HOME/.tmp"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

source_if /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-prompt.sh

export PATH="$HOME/Library/Python/3.7/bin:$PATH"
