# vim: sw=0 ts=2 noet

context.properties = {
	log.level = 2
	core.name = "meeting-virtual-montior"
	application.name = "pipewire-meeting-virtual-montior"
}

context.spa-libs = {
	audio.convert.* = audioconvert/libspa-audioconvert
	support.*       = support/libspa-support
}

context.modules = [
	{ name = libpipewire-module-rt
			args = {
					#rt.prio      = 83
					#rt.time.soft = -1
					#rt.time.hard = -1
			}
			flags = [ ifexists nofail ]
	}
	{ name = libpipewire-module-protocol-native },
	{ name = libpipewire-module-client-node },
	{ name = libpipewire-module-adapter },
]
