[colors.normal]
black = "0x222222"
red = "0xcf0002"
green = "0x00cc00"
yellow = "0xe6c540"
blue = "0x0aa6da"
magenta = "0xb043fe"
cyan = "0x70c0ba"
white = "0xffffff"

[colors.bright]
black = "0x666666"
red = "0xff3334"
green = "0x9ec400"
yellow = "0xe7c547"
blue = "0x7aa6da"
magenta = "0xb77ee0"
cyan = "0x54ced6"
white = "0xffddff"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[font.normal]
family = "InconsolataGo Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001B08"
key = "Back"
mods = "Control"

[mouse]
hide_when_typing = false

[scrolling]
multiplier = 1

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
#args = ["--login", "-c", "xonsh"]
args = ["--login"]
program = "zsh"

[window]
dynamic_padding = false
dynamic_title = true
