alias t='systemd-run -d -E TMUX_TMPDIR=$TMUX_TMPDIR --user --scope $(whence tmux) start-server'

function yay()
{
	(
		export GNUPGHOME="$HOME/.config/makepkg.gnupg"
		systemd-inhibit --mode=block --what=shutdown:sleep:idle --who=qyriad --why=yay --no-pager --no-legend yay "$@"
	)
}
