alias t='systemd-run -d -E TMUX_TMPDIR=$TMUX_TMPDIR --scope --user --uid qyriad --gid qyriad $(whence tmux) start-server'

function yay()
{
	(
		GNUPGHOME="$HOME/.config/makepkg.gnupg"
		systemd-inhibit --mode=block --what=shutdown:sleep:idle --who=qyriad --why=yay --no-pager --no-legend yay "$@"
	)
}
