# Lines configured by zsh-newuser-install
HISTFILE=$HOME/.cache/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/qyriad/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt AUTO_CONTINUE

autoload -Uz promptinit

promptinit

setopt PROMPT_SUBST

bindkey "^[[1;5C" forward-word # C-<right>
bindkey "^[[1;5D" backward-word # C-<left>
bindkey "^[[1~" beginning-of-line # <home>
bindkey "^[[4~" end-of-line # <end>
bindkey "^[[3~" delete-char # <del>

# Allow editing the command in vim
autoload -Uz edit-command-line # Load the function from ZSH runtime 
zle -N edit-command-line # Expose the function as a widget
bindkey "" "edit-command-line" # Call the widget upon <C-X><C-E>

# Add shortcut for pushing the line onto the stack
bindkey "" "push-input"

export PATH="$HOME/.local/bin:/usr/local/bin:$HOME/.local/share/cargo/bin:$PATH"

# Use neovim for everything
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"
export SYSTEMD_EDITOR="/usr/bin/nvim"
export NETCTL_EDITOR="/usr/bin/nvim"
alias vim='nvim'

# MAke stuff follow XDG
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GNUPGHOME="$XDG_CONFIG_HOME"/gnupg
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export VIMINIT=':let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
alias tmux='tmux -u -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'
export XCOMPOSEFILE="$XDG_CONFIG_HOME/X11/Xcompose"

alias cmc="rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake"
alias ec="vim CMakeLists.txt"

# Coreutils and builtins
alias ls='exa'
alias ll="ls -lh"
alias la="ls -Al"
alias cp="cp -vi"
alias rm="rm -vi"
alias mv="mv -vi"
alias ln="ln -vi"
alias chown="chown -v --preserve-root"
alias chmod="chmod -v --preserve-root"
alias chgrp="chgrp -v --preserve-root"
alias grep="grep --color=auto"
alias less="less -R"

# Tar
alias tarx="tar -xvf"
alias tart="tar -tvf"
alias tarc="tar -cvf"

# Edit config shortucts
alias et="$EDITOR $HOME/.config/tmux/tmux.conf"
alias ev="$EDITOR $HOME/.config/vim/vimrc"
alias ei3="$EDITOR $HOME/.config/i3/config"
alias eb="$EDITOR $HOME/.config/bash/bashrc"
alias ex="$EDITOR $HOME/.xinitrc"
alias exr="$EDITOR $HOME/.config/X11/Xresources"
alias ei="$EDITOR $HOME/.config/i3/config"
alias sb="source $HOME/.bashrc"
alias er="$EDITOR $HOME/.config/ranger/rc.conf"
alias ea="$EDITOR $HOME/.config/alacritty/alacritty.yml"
alias ef="$EDITOR $HOME/.config/fontconfig/fonts.conf"
alias ez="$EDITOR $HOME/.config/zsh/zshrc"
alias sz="source $HOME/.zshrc"
alias es="$EDITOR $HOME/.ssh/config"
alias ek="$EDITOR $HOME/.config/kitty/kitty.conf"
alias etr="$EDITOR $HOME/.config/termite/config"

# Misc
alias wgetc="wget --content-disposition" # Uses server filename across redirects
alias ni="nonet"
alias info="pinfo"
alias sudoe="sudo -E" # I shouldn't always, but sometimes it's really nice to preserve env when editing
alias sudos="sudo -Es"
alias gpc='gpaste-client'
alias sgpc='xargs gpaste-client add'
alias cdconf='cd $HOME/.config'
alias xdgo='xdg-open'
alias ffprobe="ffprobe -hide_banner"
alias ffmpeg='ffmpeg -hide_banner'
alias prp='realpath .' # "Print real path"
alias tn="tr -d '\n'" # Strip newlines, meant to be used when copying one line of command output to clipboard
alias remake='mkdir $(pwd) ; cd $(pwd)'
alias svim="sudo -E nvim"
alias vrt='nvr --remote-silent -sp' # Vim Remote Tab
alias yay='GNUPGHOME=$HOME/.config/makepkg.gnupg yay'
alias xxpreview='xxd -l 512'
#alias lsync='rsync -av --no-o --no-p --no-g --info=progress2'
alias lsync='rsync -rvlh --info=progress2'
alias what='whence -sav' # show symlinks too
#alias built-in-man='vim "+tab Man zshall | normal
alias ps='ps --forest'
alias lsdsk='lsblk -o NAME,FSTYPE,LABEL,TYPE,MOUNTPOINT'
alias lsd='lsblk -o NAME,FSTYPE,LABEL,TYPE,MOUNTPOINT'
alias wine32="WINEPREFIX=$HOME/.wine32 WINEARCH=win32 wine"
alias winetricks32="WINEPREFIX=$HOME/.wine32 WINEARCH=win32 winetricks"

function appfd()
{
	fd "$1" /usr/share/applications ~/.local/share/applications
}

function tmuxman()
{
	man tmux | vim "+set ft=man | normal /\v^\s+$1 (\[|-)"
}

function vimman()
{
	man $1 | vim "+set ft=man"
}

function zshman()
{
	man zshall | vim "+set ft=man | normal /\v^\s+$1 (\[|-)"
}

function source_if()
{
	[ -r "$1" ] && source "$1"
}

source /usr/share/git/completion/git-prompt.sh
autoload -Uz vcs_info

precmd()
{
	vcs_info
}

zstyle ':vcs_info:git*' formats '%F{116}(%b)'
zstyle ':vcs_info:git*' actionformats '%F{116}(%b|%a)'

export PROMPT='%F{2}%n@%m %F{129}%~${vcs_info_msg_0_:+ ${vcs_info_msg_0_}} %F{2}%(! # $) %f'

zstyle ':completion:*:*:git:*' script /usr/share/git/completion/git-completion.zsh

#source_if /usr/share/git/completion/git-completion.zsh
source_if /usr/share/git/completion/git-prompt.sh
source_if /etc/profile.d/cnf.sh
source_if /etc/profile.d/devkitarm.sh
source_if /etc/profile.d/devkitppc.sh


source_if /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source_if /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

source /usr/share/zsh/scripts/zplug/init.zsh

source_if $HOME/.local/bin/zsh_automatic_cd.zsh && bindkey -s '' 'ranger' && alias ranger='ranger-cd'

unalias run-help
autoload -Uz run-help

if [ -z "$TMUX" ]; then # If we're not already in a tmux session
	if [ "$(tty)" != "/dev/tty1" ]; then # and we're not in tty1
		if tmux list-sessions; then # if there's a session, attach
			tmux attach-session -d
		else
			tmux # otherwise, create one
		fi
	fi
fi
