# vim: sw=0 ts=2 noet
context.modules = [
	#{
	#	name = libpipewire-module-filter-chain
	#	args = {
	#		node.description = "All Meeting Audio"
	#		media.name = "All Meeting Media"
	#
	#		filter.graph = {
	#			nodes = {
	#				type = builtin
	#				name = mixer
	#				plugin = mixer
	#				label = mixer
	#				control = { }
	#			}
	#		}
	#	}
	#}
	{
		name = libpipewire-module-combine-stream
		args = {
			node.name = "meeting-combination"
			node.description = "Record this for all meeting audio"

			combine.mode = source
			combine.latency-compensate = true

			combine.props = {
				audio.position = [ FL FR ]
				resample.disable = false

				media.name = "Meeting Audio Collector"
				media.role = "Communication"

				# Make the name nicer.
				# Must match all of these.
				node.group = "combine-source-meeting-audio-collector"
				node.link-group = "combine-source-meeting-audio-collector"
			}

			stream.rules = [
				# Match our microphone and create a stream for it.
				{
					matches = [ {
							# Our microphone
							media.class = "Audio/Source"
							node.name = "alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y7Y663P27FB970-00.Direct__Direct__source"
					} ]
					actions = { create-stream = {
						audio.position = [ FL FR ]
						combine.audio.position = [ FL FR ]

						resample.disable = false

						node.group = "combine-source-meeting-audio-collector"
						node.link-group = "combine-source-meeting-audio-collector"

						# Cosmetic.
						media.name = "Capture of Microphone for Meetings"
					} }
				}

				# Match the *monitor* of our speakers.
				{
					matches = [ {
						media.class = "Audio/Sink"
						node.name = "alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y7Y663P27FB970-00.Direct__Direct__sink"
					} ]
					actions = { create-stream = {
						audio.position = [ FL FR ]
						combine.audio.position = [ FL FR ]
						stream.capture.sink = true

						resample.disable = false

						node.group = "combine-source-meeting-audio-collector"
						node.link-group = "combine-source-meeting-audio-collector"

						# Cosmetic.
						media.name = "Capture of :MONITOR: for Speakers for Meetings"
					} }
				}
			]
		}
	}
]
