# vim: sw=0 ts=2 noet
context.modules = [
	{
		name = libpipewire-module-loopback
		flags = [ nofail ]
		args = {
			node.name = "loopback.capturecard"
			node.description = "Elgato HD60 S+ Loopback"
			media.name = "Elgato HD60 S+ Game Audio"
			#media.role = "Game"

			# Just for display.
			device.form-factor = "tv"

			capture.props = {
				target.object = "alsa_input.usb-Elgato_Game_Capture_HD60_S__0004C809C2000-03.analog-stereo"

				node.group = "external-game-audio"
				node.link-group = "external-game-audio"

				node.dont-fallback = true

				# If the capture card isn't plugged in, don't destroy this node.
				# Instead, wait for the capture card to come up.
				node.linger = true

				#media.class = "Audio/Sink"
				media.class = "Stream/Input/Audio"
				node.virtual = true
				stream.capture.sink = false
				monitor.channel-volumes = false

				node.description = "Elgato HD60 S+ virtual sink"
				device.icon-name = "tv"
				media.icon-name = "tv"

				# DON'T allow, like, trying to set this as the default output.
				node.dont-move = true

				# Don't force scheduling with the rest of the system.
				# idk if this actually does anything.
				node.loop.name = "data-loop.1"

				# I need to match these or it won't link.
				audio.position = [ FL FR ]
			}

			playback.props = {
				media.class = "Stream/Output/Audio"
				#media.class = "Audio/Source"
				application.name = "Game Audio Loopback"
				application.process.user = "qyriad"

				target.object = "alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y7Y663P27FB970-00.Direct__Direct__sink"

				node.group = "external-game-audio"
				node.link-group = "external-game-audio"

				stream.capture.sink = false
				monitor.channel-volumes = false

				node.loop.name = "data-loop.1"

				node.description = "Elgato HD60S+ virtual output stream"
				device.icon-name = "tv"
				media.icon-name = "tv"

				# I need to match these or it won't link.
				audio.position = [ FL FR ]
			}
		}
	}
]
#context.modules = [
#	{
#		name = libpipewire-module-loopback
#		flags = [ nofail ]
#		args = {
#			node.name = loopback.capturecard
#			node.description = "Elgato HD60 S+ Audio"
#			#node.min-latency = "2048/48000"
#			#node.min-quantum = 1024
#			#node.latency = "8192/48000"
#			#node.latency = "9600/48000" # 200 milliseconds
#			node.latency = "7200/48000" # 150 milliseconds
#			#node.lock-quantum = false
#			#node.suspend-on-idle = true
#			media.name = "Elgato HD60 S+ Audio"
#			media.role = "Game"
#
#			# Just for display.
#			device.form-factor = "tv"
#			#device.bus = "usb"
#
#			capture.props = {
#				target.object = "alsa_input.usb-Elgato_Game_Capture_HD60_S__0004C809C2000-03.analog-stereo"
#				#object.linger = true # ?
#				resample.disable = false
#
#				# The stream is monitoring and might select a less accurate but faster conversion algorithm.
#				#stream.monitor = true
#			}
#			playback.props = {
#				#dont-fallback = true
#				target.object = default.audio.sink
#				resample.disable = false
#
#				# According to Wireplumber comments, this must be set to ensure that the real audio sink
#				# is suspended when there is no active client stream linked.
#				node.passive = true
#
#				# According to Wireplumber comments, using an unused role makes sure that loopbacks
#				# don't accidentally chain-link to one another.
#				media.role = "Loopback"
#
#				# The stream is monitoring and might select a less accurate but faster conversion algorithm.
#				#stream.monitor = true
#			}
#		}
#	}
#]
