#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PATH=~/.local/bin:$PATH:/usr/local/bin:~/.local/share/cargo/bin:$DEVKITARM/bin

# Use vim for everything
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export SYSTEMD_EDITOR="/usr/bin/vim"
export NETCTL_EDITOR="/usr/bin/vim"

# Make stuff follow XDG
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GNUPGHOME="$XDG_CONFIG_HOME"/gnupg
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
#export VIMINIT=':let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export VIMCONFIG="$XDG_CONFIG_HOME/vim"
alias tmux='tmux -u -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'

# High DPI
#export GTK_SCALE=2

# Set default compiler stuff
#export CC=clang
#export CXX=clang++
#export CFLAGS="-Wall -Wextra -pedantic -g3 -Og"
#export CXXFLAGS="-Wall -Wextra -pedantic -g3 -Og"

alias cmc="rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake"
alias ec="vim CMakeLists.txt"

# Coreutils and builtins
alias ls='exa'
alias ll="ls -lh"
alias la="ls -Al"
alias cp="cp -vi"
alias rm="rm -vi"
alias mv="mv -vi"
alias ln="ln -vi"
alias chown="chown --preserve-root"
alias chmod="chmod --preserve-root"
alias chgrp="chgrp --preserve-root"
alias grep="grep --color=auto"
alias less="less -R"

# Tar
alias tarx="tar -xvf"
alias tart="tar -tvf"
alias tarc="tar -cvf"

# Edit config shortucts
alias et="vim ~/.config/tmux/tmux.conf"
alias ev="vim ~/.config/vim/vimrc"
alias ei3="vim ~/.config/i3/config"
alias eb="vim ~/.config/bash/bashrc"
alias ex="vim ~/.xinitrc"
alias exr="vim ~/.config/X11/Xresources"
alias ei="vim ~/.config/i3/config"
alias sb="source ~/.bashrc"
alias er="vim ~/.config/ranger/rc.conf"
alias ea='vim ~/.config/alacritty/alacritty.yml'
alias ef='vim ~/.config/fontconfig/fonts.conf'

# Misc
alias wgetc="wget --content-disposition" # Uses server filename across redirects
alias ni="nonet"
alias info="pinfo"
alias sudoe="sudo -E" # I shouldn't always, but sometimes it's really nice to preserve env when editing
#alias sudo="sudo -E" # screw it
alias sudos="sudo -Es"
alias gpc='gpaste-client'
alias sgpc='xargs gpaste-client add'
alias cdconf='cd ~/.config'
alias xdgo='xdg-open'
alias ffprobe="ffprobe -hide_banner"
alias ffmpeg='ffmpeg -hide_banner'
alias prp='realpath .' # "Print real path"
alias tn="tr -d '\n'" # Strip newlines, meant to be used when copying one line of command output to clipboard
alias remake='mkdir $(pwd) ; cd $(pwd)'
alias svim='sudo -E vim'
alias videoctl='v4l2-ctl'

# Directory shortucts
export lorddir="/media/qyriad/lord"
export gamesdir="$lorddir/Games"


function show()
{
	grep -E --color=always "$1|"
}

function source_if()
{
	[ -r "$1" ] && source "$1"
}

source_if /usr/share/doc/ranger/examples/bash_automatic_cd.sh

alias ranger='ranger-cd'

[ -r /usr/share/git/completion/git-completion.bash ] && source /usr/share/git/completion/git-completion.bash
[ -r /usr/share/git/completion/git-prompt.sh ] && source /usr/share/git/completion/git-prompt.sh
[ -r /etc/profile.d/cnf.sh ] && source /etc/profile.d/cnf.sh
[ -r /etc/profile.d/devkitarm.sh ] && source /etc/profile.d/devkitarm.sh
[ -r /etc/profile.d/devkitppc.sh ] && source /etc/profile.d/devkitppc.sh

alias savepng="xclip -f image/png -selection clipboard -o > \"\$(date +\"%Y-%m-%d-%H-%M-%S\").png\""

# Explanation: list x clients; don't match in color; only display the parts that match; use pcre; 
# (Any amount of whitespace; 'Command:'; any amount of whitespace) <-- don't match that, just assert it
# Match any sequence of alphabetical characters given the previous assertion
alias xlsprograms='xlsclients -l | grep --color=never -oxP "(\s+Command:\s+)\K[a-zA-Z]+"'
alias lsnoxprograms='ps x | grep -v -e "$(xlsprograms)" -e "X11" -e "xorg" -e "Xorg" -e "startx" -e "xinit"'
alias lsxfilter='grep $(for p in $(xlsprograms); do echo "-e $p"; done)'

set -C # Disallow overriting on >, require >| to override that

function vi()
{
	echo "Nope."
}

[ -r ~/.config/bash/colors.bash ] && source ~/.config/bash/colors.bash

ttystr="$(tty | sed -E 's|/dev/pts..?||' | cut -c6-)"
if [ -n "$ttystr" ]; then
	tty=".$ttystr"
else
	tty=""
fi

if [ "$(tput colors)" -lt 256 ]; then
	SUDO_COLOR="\[\e[0;36m\]"
else
	SUDO_COLOR="\[\e[38;5;39m\]"
fi

if [[ $SUDO_USER ]]; then
	PS1="$SUDO_COLOR\u@\h$tty\[\e[m\] \[\e[38;5;129m\]\w\[\e[m\]\[\033[36m\]"'`__git_ps1`'"\[\e[0;32m\] \$\[\e[0;37m\] "
elif [ "$EUID" = 0 ]; then
	PS1="\[\e[0;31m\]\u@\h$tty\[\e[m\] \[\e[38;5;129m\]\w\[\e[m\]\[\033[36m\]"'`__git_ps1`'"\[\e[0;32m\] \$\[\e[0;37m\] "
else
	PS1="\[\e[32m\]\u@\h$tty\[\e[m\] \[\e[38;5;129m\]\w\[\e[m\]\[\033[36m\]"'`__git_ps1`'"\[\e[0;32m\] \$\[\e[0;37m\] "
fi

export WUT_ROOT=/usr
alias cmakewii="cmake -DCMAKE_TOOLCHAIN_FILE=$WUT_ROOT/cmake/wut-toolchain.cmake"
alias lsync="rsync -av --no-o --no-p --no-g --progress"
alias funkiiu="FunKiiU"

# Tab completion stuff
bind 'TAB:menu-complete'
bind 'set show-all-if-ambiguous on'
bind 'set menu-complete-display-prefix on'
bind 'set completion-ignore-case on'

function git_commit()
{
	tmux split-window -v && tmux send-keys "git" Space "commit && exit"
}

if [ "$EUID" = 0 ]; then
	return
fi

if [ -n "$thunar" ]; then
	unset thunar
	tmux new-window
	tmux attach-session
	return
fi

if [ -z "$TMUX" ]; then # if we're not already in a tmux session
	if [ "$(tty)" != "/dev/tty1" ]; then # and we're not in tty1
		if tmux list-sessions; then # if there's a session, attach
			tmux attach-session -d
		else
			tmux # otherwise, create one
		fi
	fi
fi
