# vim: shiftwidth=4 tabstop=4 noexpandtab
# Do not modify this file!	It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
		./disko.nix
	];

	boot.initrd.availableKernelModules = [
		"nvme"
		"xhci_pci"
		"ahci"
		"usbhid"
		"usb_storage"
		"sd_mod"
	];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [
		"kvm-amd"
		"nvidia"
	];
	boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
	services.xserver.videoDrivers = [
		"nvidia"
	];

	warnings = let
		latest = pkgs.linuxPackages_latest.kernel.version;
		current = pkgs.linuxPackages_6_17.kernel.version;
	in lib.mkIf (latest != current) [
		"Yuki's Linux (6.17) is no longer latest (${latest})"
	];

	boot.kernelPackages = pkgs.linuxPackages_6_17;

	hardware.nvidia = {
		modesetting.enable = true;
		package = config.boot.kernelPackages.nvidiaPackages.beta;
		open = true;
		powerManagement.enable = true;
	};
	hardware.graphics.enable32Bit = true;

	boot.swraid.mdadmConf = lib.optionalString config.boot.swraid.enable <| lib.dedent ''
		MAILADDR qyriad@qyriad.me
	'';


	#fileSystems."/" = {
	#	device = "/dev/disk/by-uuid/4a86932f-5e2d-464e-9699-cde6d010847d";
	#	fsType = "ext4";
	#	options = [ "discard" "lazytime" "data=writeback" ];
	#};
	#
	#fileSystems."/boot/efi" = {
	#	device = "/dev/disk/by-uuid/137E-C800";
	#	fsType = "vfat";
	#};

	# All partitions of GPT type "Linux swap", per the Linux Userspace API Group's
	# Discoverable Partitions Speficiation, will be automatically `swapon()`'d, by
	# systemd-gpt-auto-generator(8).
	#swapDevices = [ ];
	#
	#boot.resumeDevice = "/dev/disk/by-label/I660-Swap-FS";

	# Does… this do anything?
	hardware.deviceTree.enable = true;

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

